from gpiozero import LED
from time import sleep

led_1 = LED(4)
led_2 = LED(17)
led_3 = LED(27)
led_4 = LED(22)
led_5 = LED(5)
led_6 = LED(6)
led_7 = LED(13)
led_8 = LED(19)

while True:
    led_1.on()
    sleep(0.1)
    led_1.off()
    led_2.on()
    sleep(0.1)
    led_2.off()
    led_3.on()
    sleep(0.1)
    led_3.off()
    led_4.on()
    sleep(0.1)
    led_4.off()
    led_5.on()
    sleep(0.1)
    led_5.off()
    led_6.on()
    sleep(0.1)
    led_6.off()
    led_7.on()
    sleep(0.1)
    led_7.off()
    led_8.on()
    sleep(0.1)
    led_8.off()
    led_7.on()
    sleep(0.1)
    led_7.off()
    led_6.on()
    sleep(0.1)
    led_6.off()
    led_5.on()
    sleep(0.1)
    led_5.off()
    led_4.on()
    sleep(0.1)
    led_4.off()
    led_3.on()
    sleep(0.1)
    led_3.off()
    led_2.on()
    sleep(0.1)
    led_2.off()